django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuario.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('usuario/', include('usuario.urls')),
    path("comunidade/", include("comunidade.urls")),
    path("musica/", include("musica.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musica/urls.py
from django.urls import path
from comunidade.views import community_preview
from musica import views

urlpatterns = [
    path('', views.pesquisa_musica, name='buscar_musicas'),
    path('player/', views.player, name='player'),
    path('player-comunidade/',views.player_comunidade,name='player_comunidade'),
    path('playerCurtir/', views.player, name='playerCurtir'),
    path('salvar/', views.salvar_musica, name='salvar_musica'),
    path('playlists/', views.listar_playlists_usuario, name='listar_playlists'),
    path('playlists/', views.listar_playlists_todos, name='listar_playlists_todos'),
    path('playlists/todos/', views.listar_playlists_todos, name='listar_playlists_todos'),
    path('busca-usuario/', views.buscar_usuario_view, name='buscar_usuario_view'),
    path('busca-comunidade/', views.buscar_comunidade, name='buscar_comunidade'),
    path("comunidade/<str:nome_tag>/community_preview", community_preview, name="community_preview"),
    path('playlist/<int:playlist_id>/', views.ver_playlist, name='ver_playlist'),
    path('playlist/<int:playlist_id>/excluir/', views.excluir_playlist, name='excluir_playlist'),
    path('criar_playlist/', views.criar_playlist, name='criar_playlist'),
    path('playlist/curtidas/', views.adicionarMusicasFavoritas, name='adicionarMusicasFavoritas'),
    path('playlist/descurtir/', views.excluirMusicasFavoritas, name='excluirMusicasFavoritas'),
    path('player/playlist/descurtir/', views.excluirMusicasFavoritas, name='excluirMusicasFavoritasPlayer'),
    path('player/playlist/curtidas/', views.adicionarMusicasFavoritas, name='adicionarMusicasFavoritasPlayer'),
    path('player-comunidade/playlist/descurtir/', views.excluirMusicasFavoritas, name='excluirMusicasFavoritasPlayer'),
    path('player-comunidade/playlist/curtidas/', views.adicionarMusicasFavoritas, name='adicionarMusicasFavoritasPlayer'),
    path('editar_playlist/<int:playlist_id>/editar/', views.editar_playlist, name='editar_playlist'),
    path('playlist/<int:playlist_id>/remover_musica/<int:musica_id>/', views.remover_musica_da_playlist, name='remover_musica_da_playlist'),
]

usuario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastro/', views.cadastro_view, name='cadastro'),
    path('login/' , views.login_view, name='login'),
    path('perfil/<str:username>/', views.perfil_view, name='perfil'),
    path('perfil-config/', views.perfil_config_view, name='perfil_config'),
    path('genero/', views.genero_view, name='genero'),
    path('logout/', views.logout_view, name='logout'),
    path('principal/', views.principal_view, name='principal'),
    path('buscar-usuario/', views.buscar_usuario_view, name='buscar-usuario'),
    path('seguir/', views.seguir_view, name='seguir'),
]

usuario/models.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nascimento = models.DateField(null=True, blank=True)
    generos_musicas = models.CharField(max_length=200, null=True, blank=True)
    biografia = models.TextField(null=True, blank=True)  # CLOB no Oracle, cuidado com buscas
    privacidade = models.IntegerField(default=1, choices=[(0, 'Privado'), (1, 'Público')])  # substitui BooleanField
    imagem_perfil = models.URLField(blank=True, null=True, default="https://tfavf9hmcaamd4yg.public.blob.vercel-storage.com/95e4a5e0-d81a-44d2-882b-ef0098a9235a.png")
    imagem_perfil_hash = models.CharField(max_length=64, blank=True, null=True,default="ccaae35952063bd7e441640ebfe236041947d7a9ef42576a5fc2e024a6e6be95")  # Hash da imagem para evitar duplicatas

    def __str__(self):
        return self.user.username
    
class Seguidor(models.Model):
    usuario = models.ForeignKey(User, related_name='seguidores', on_delete=models.CASCADE)
    seguidor = models.ForeignKey(User, related_name='seguidos', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('usuario', 'seguidor')  # Impede duplicatas
        verbose_name = 'Seguidor'
        verbose_name_plural = 'Seguidores'

    def __str__(self):
        return f'{self.seguidor.username} segue {self.usuario.username}'

usuario/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
import re
from .models import Profile

User = get_user_model()

class CadastroForm(forms.Form):
    primeiro_nome = forms.CharField(max_length=30, label="Nome")
    sobrenome = forms.CharField(max_length=150, label="Sobrenome")
    usuario = forms.CharField(max_length=150, label="Usuário")
    email = forms.EmailField(max_length=255, required=True, label="E-mail")
    senha = forms.CharField(widget=forms.PasswordInput, label="Senha")
    confirmacao = forms.CharField(widget=forms.PasswordInput, label="Confirmação de Senha")

    def clean_usuario(self):
        usuario = self.cleaned_data['usuario']
        if ' ' in usuario or len(usuario) < 5:
            raise ValidationError("Usuário inválido.")
        if User.objects.filter(username=usuario).exists():
            raise ValidationError("Este nome de usuário já está em uso.")
        return usuario

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este e-mail já está cadastrado.")
        return email

    def clean(self):
        dados = super().clean()
        senha = dados.get('senha')
        confirmacao = dados.get('confirmacao')

        if senha:
            if (
                len(senha) < 5 or
                not re.search(r'[a-z]', senha) or
                not re.search(r'[A-Z]', senha) or
                not re.search(r'[0-9]', senha)
            ):
                self.add_error('senha', "A senha deve ter maiúsculas, minúsculas e números.")
        
        if senha != confirmacao:
            self.add_error('confirmacao', "As senhas não coincidem.")
        return dados




class LoginForm(forms.Form):
    email = forms.EmailField(label="Email")
    senha = forms.CharField(widget=forms.PasswordInput, label="Senha")
    
class ProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = Profile
        fields = ['nascimento', 'biografia', 'privacidade']
        widgets = {
            'nascimento': forms.DateInput(attrs={'type': 'date'}),
            'biografia': forms.Textarea(attrs={'rows': 4}),
        }

usuario/views.py
# views.py
import requests
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import CadastroForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from usuario.models import Profile, Seguidor
from .forms import ProfileForm
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.conf import settings
from django.utils.timezone import now
from django_project.utils import upload_vercel_image
from musica.models import Playlist

def cadastro_view(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST)
        if form.is_valid():
            novo_usuario = User.objects.create_user(
                username=form.cleaned_data['usuario'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['senha'],
                first_name=form.cleaned_data['primeiro_nome'],
                last_name=form.cleaned_data['sobrenome']
            )
            Profile.objects.create(user=novo_usuario)
            return redirect('login')
    else:
        form = CadastroForm()

    return render(request, 'usuarios/cadastro.html', {'form': form})



def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            senha = form.cleaned_data['senha']

            try:
                user_obj = User.objects.get(email=email)
                user = authenticate(request, username=user_obj.username, password=senha)
            except User.DoesNotExist:
                user = None

            if user is not None:
                login(request, user)
                return redirect('principal')
            else:
                form.add_error(None, "Credenciais inválidas.")
    else:
        form = LoginForm()

    return render(request, 'usuarios/login.html', {'form': form})

@login_required
def perfil_view(request, username):
    usuario = get_object_or_404(User, username=username)
    perfil = get_object_or_404(Profile, user=usuario)

    # Verifica se o usuário logado é o dono do perfil
    is_owner = request.user == usuario

    # Verifica se o perfil é privado
    is_private = perfil.privacidade == 0
    # Contagem de seguidores: Quantos estão seguindo o 'usuario'
    seguidores_count = Seguidor.objects.filter(usuario=usuario).count()
    
    # Contagem de seguidos: Quantos o 'usuario' está seguindo
    seguindo_count = Seguidor.objects.filter(seguidor=usuario).count()

    # Verifica se o usuário logado está seguindo o dono do perfil
    is_following = False
    if not is_owner:
        is_following = Seguidor.objects.filter(
            usuario=usuario,
            seguidor=request.user
        ).exists()
        
    is_followed_by_user = Seguidor.objects.filter(seguidor=usuario, usuario=request.user).exists()

    context = {
        'usuario': usuario,
        'seguidores_count': seguidores_count,
        'seguindo_count': seguindo_count,
        'perfil': perfil,
        'is_owner': is_owner,
        'is_private': is_private,
        'is_following': is_following,
        'is_followed_by_user': is_followed_by_user,
        'now': now(),  # Passa a data e hora para o template, se necessário
    }
    context['bloquear_acesso'] = context['is_private'] and (
    not context['is_following'] or not context['is_followed_by_user']
    )
    return render(request, 'usuarios/perfil.html', context)


@login_required    
def perfil_config_view(request):
    # Obtém ou cria o perfil do usuário
    perfil, _ = Profile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=perfil)

        if form.is_valid():
            # Verifica se há uma imagem de perfil
            profile_picture = form.cleaned_data.get('profile_picture')

            if profile_picture:
                # Chama a função para fazer o upload da imagem para o Vercel
                upload_dict = upload_vercel_image(profile_picture)

                if upload_dict["erro"]:
                    form.add_error('profile_picture', 'Erro ao fazer o upload da imagem.')
                else:
                    # Atualiza o perfil com a URL e o hash da imagem
                    perfil.imagem_perfil = upload_dict["url"]
                    perfil.imagem_perfil_hash = upload_dict["file_hash"]

            # Salva as alterações no perfil
            form.save()
            return redirect('perfil', username=request.user.username)

    else:
        # Caso seja uma requisição GET, exibe o formulário com os dados atuais
        form = ProfileForm(instance=perfil)

    # Renderiza a página com o formulário de perfil
    return render(request, 'usuarios/perfil-config.html', {
        'form': form,
        'perfil': perfil,
    })





    
@login_required
@require_POST
def seguir_view(request):
    user_id = request.POST.get('user_id')
    try:
        usuario = User.objects.get(id=user_id)
    except User.DoesNotExist:
        return JsonResponse({'error': 'Usuário não encontrado'}, status=404)

    # Verifica se já está seguindo
    seguindolink = Seguidor.objects.filter(usuario=usuario, seguidor=request.user)

    if seguindolink.exists():
        # Se já segue, remove (desseguir)
        seguindolink.delete()
        status = 'unfollowed'
    else:
        # Caso contrário, cria a relação (seguir)
        Seguidor.objects.create(usuario=usuario, seguidor=request.user)
        status = 'followed'

    return JsonResponse({'status': status})


@require_POST
def logout_view(request):
    print("Logout foi chamado!")
    logout(request)
    return redirect('login')    

@login_required
def genero_view(request):
    print("entrou na view genero")

    if request.method == 'POST':
        print("entrou no if do post")
        # Captura os dados enviados via POST
        dados = request.POST.get('selectedGenres')  # Aqui estamos capturando o valor enviado como selected_Genres
        print(f"Dados recebidos: {dados}")  # Apenas para depuração, você pode remover isso mais tarde
        if dados:
            print(dados)  # Apenas para depuração, você pode remover isso mais tarde
            Profile.objects.filter(id=request.user.id).update(generos_musicas=dados)
            # Aqui você pode adicionar a lógica para processar os dados, como salvar no banco de dados ou outra operação
            return JsonResponse({'message': 'Dados recebidos com sucesso!'})
        else:
            return JsonResponse({'error': 'Nenhum dado foi enviado.'}, status=400)
    
    return render(request, 'usuarios/genero.html')


def home(request):
    return render(request, 'usuarios/home.html')

@login_required
def principal_view(request):
    playlists_destaques = playlists_destaque()
    return render(request, 'usuarios/principal.html', {'playlists_destaque': playlists_destaques})



@login_required
def buscar_usuario_view(request):
    usuarios = []
    busca = ''
    if request.method == 'POST':
        busca = request.POST.get('usuario', '')
        usuarios = User.objects.filter(username__icontains=busca)[:10]
    return render(request, 'usuarios/buscar-usuario.html', {'usuarios': usuarios, 'busca': busca})

def playlists_destaque():
    nomes = ['Pop', 'Rock', 'Hip-Hop', 'Eletrônica', 'Blues', 'Clássica', 'Jazz', 'Reggae', 'Pagode', 'Sertanejo']
    return Playlist.objects.filter(nome__in=nomes)

usuario/templates/usuarios/buscar-usuario.html
<!DOCTYPE html>
<html>
<head>
    <title>Buscar Usuário</title>
</head>
<body>
    <h1>Buscar Usuário</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <label for="usuario">Nome:</label>
        <input type="text" id="usuario" name="usuario" value="{{ busca }}">
        <button type="submit">Buscar</button>
        <link rel="icon" type="image/x-icon" href="{% static 'app/imagens/favicon.ico' %}">
    </form>

    {% if usuarios %}
        <h2>Resultados:</h2>
        <ul>
            {% for usuario in usuarios %}
                <li><a href="{% url 'perfil' usuario.username %}">{{ usuario.username }}</a></li>
            {% endfor %}
        </ul>
    {% elif busca %}
        <p>Nenhum usuário encontrado para "{{ busca }}"</p>
    {% endif %}
</body>
</html>

usuario/templates/usuarios/cadastro.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/material_blue.css">
    <link rel="stylesheet" href="{% static 'app/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'app/imagens/favicon.ico' %}">
    <style>
        body {
            background: linear-gradient(
                to bottom right,
                 #5A005A,
                  #620077,
                   #7117B8,
                    #7932DE,
                     #8977FF,
                      #B6B2FF); 
            font-family: Montserrat, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 2rem 1rem;
            min-height: 100vh;
            height: auto;
        }
    
        h1 {
            font-size: 1.8rem;
            margin-bottom: 1rem;
            margin-top: 10px;
            color: white;
        }
    
        form {
            width: 100%;
            max-width: 400px;
            background-color: rgba(255, 255, 255, 0.3);
            padding: 2rem;
            border-radius: 12px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.05);
            text-align: center;
            border: 0.3px solid white;
            color:white;

        }
    
        form p {
            display: flex;
            flex-direction: column;
            margin-bottom: 0rem;
            text-align: left;
        }
    
        form label {
            font-weight: 500;
            margin-bottom: 0.3rem;
            font-size: 0.9rem;
        }
    
        form input,
        form textarea,
        form select {
            padding: 0.5rem 0.75rem;
            border: 1px solid #ccc;
            border-radius: 8px;
            font-size: 1rem;
            width: 100%;
            box-sizing: border-box;
        }
    
        button[type="submit"] {
    margin: 0rem auto 0 auto; /* Centraliza horizontalmente e dá espaçamento acima */
    background-color: #7932DE;
    color: white;
    border: none;
    border-radius: 50%;
    width: 50px;
    height: 50px;
    font-size: 1.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
}

    
        button[type="submit"]::after {
            content: "→";
        }
    
        a {
            margin-top: 1rem;
            display: block;
            text-align: center;
            font-size: 0.95rem;
        }
    
        a button {
            background: none;
            border: none;
            color: white;
            font-weight: bold;
            text-decoration: underline;
            cursor: pointer;
        }
    
        @media (max-width: 480px) {
            form {
                padding: 1.5rem 1rem;
            }
        }
        .top-section {
            height:150px;
            width: 170px;
        }
        .top-section .logo {
      width: 180px;
      height: auto;
      border-radius: 100%;
    }
    </style>    
</head>
<body>
    <div class="top-section">
        <img class="logo" src="{% static 'app/imagens/logo-branco.png' %}" alt="Logo">
      </div>
    
    <h1>Crie sua conta</h1>

    <form method="post">
        {% csrf_token %}

        <p>{{ form.primeiro_nome.label_tag }} {{ form.primeiro_nome }}</p>
        <p>{{ form.sobrenome.label_tag }} {{ form.sobrenome }}</p>
        <p>{{ form.usuario.label_tag }} {{ form.usuario }}</p>
        <p>{{ form.email.label_tag }} {{ form.email }}</p>
        <p>{{ form.senha.label_tag }} {{ form.senha }}</p>
        <p>{{ form.confirmacao.label_tag }} {{ form.confirmacao }}</p>
        <p>{{ form.nascimento.label_tag }} {{ form.nascimento }}</p>
        <p>{{ form.generos_musicas.label_tag }} {{ form.generos_musicas }}</p>
        <p>{{ form.biografia.label_tag }} {{ form.biografia }}</p>
        <p>{{ form.privacidade.label_tag }} {{ form.privacidade }}</p>

        <button type="submit"></button>
    </form>

    {% if form.errors %}
        <div style="color: red;">
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <a href="{% url 'login' %}">
        <button>Você já tem cadastro? Clique aqui</button>
      </a>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    <script>
        flatpickr("#id_nascimento", {
            dateFormat: "Y-m-d",
            maxDate: "today",
            locale: "pt"
        });
    </script>
</body>
</html>

usuario/templates/usuarios/perfil.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% load static %}
    <meta charset="UTF-8">  
    <title>Perfil</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'app/css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        <link rel="icon" type="image/x-icon" href="{% static 'app/imagens/favicon.ico' %}">
    <style>
        body {
            background: linear-gradient(
                to bottom right,
                 #5A005A,
                  #620077,
                   #7117B8,
                    #7932DE,
                     #8977FF,
                      #B6B2FF);
            font-family: Montserrat, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            height: auto;
            position: relative;
        }

        .container {
            max-width: 600px;
            background: rgba(255, 255, 255, 0.3);
            padding: 2rem;
            border-radius: 12px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            width: 90%;
            margin-bottom: 100px;
            border:0.3px solid white;
        }

        h2 {
            text-align: center;
            margin-bottom: 1.5rem;
            font-size: 1.5rem;
            font-weight: 600;
            color:white;
        }

        .info-bloco {
            background-color: #f1f3f5;
            padding: 1rem;
            border-radius: 8px;
            margin-bottom: 1rem;
        }

        .btn-config {
            display: block;
            margin: 1rem auto;
            background-color: #5A005A;
            color: white;
            padding: 0.5rem 1.25rem;
            border-radius: 8px;
            text-decoration: none;
            text-align: center;
            width: fit-content;
        }

        .btn-config:hover {
            background-color: #7932DE;
        }

        .button-group {
            text-align: center;
        }

        .top-section {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%; 
            margin-bottom: 1rem;
        }

        .top-section .logo {
            width: 180px;
            height: auto;
            border-radius: 100%;
        }

        /* Estilo para o botão de voltar no canto superior direito */
        .btn-back {
            position: absolute;
            top: 10px;
            left: 10px;
            background-color: rgb(189, 102, 240);
            color: white;
            border: none;
            border-radius: 50%;
            padding: 10px 15px;
            font-size: 16px;
            cursor: pointer;
            z-index: 10;
        }

        .btn-back:hover {
            background-color: #c94e30;
        }

        .user-profile-picture{
        width: 100px; 
        height: 100px; 
        object-fit: cover; 
        border-radius: 50%;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="top-section">
            {% if perfil.imagem_perfil %}
                <img class=" user-profile-picture" src="{{ perfil.imagem_perfil }}?v={{ now|date:'U' }}" alt="Foto de Perfil">
            {% else %}
                <img class=" user-profile-picture" src="{% static 'app/imagens/foto-padrao.jpg' %}" alt="Foto Padrão">
            {% endif %}
        </div>

        <h2>{{ usuario.username }}</h2>

        <div class="info-bloco">
            <p><strong>Nome:</strong> {{ usuario.first_name }} {{ usuario.last_name }}</p>
        </div>

        {% if is_owner %}
            <!-- O perfil do próprio usuário está sempre visível -->
            <div class="info-bloco">
                <p><strong>Email:</strong> {{ usuario.email }}</p>
                {% if perfil.nascimento %}
                    <p><strong>Nascimento:</strong> {{ perfil.nascimento }}</p>
                {% endif %}
                {% if perfil.generos_musicas %}
                    <p><strong>Gêneros Musicais:</strong> {{ perfil.generos_musicas }}</p>
                {% endif %}
                {% if perfil.biografia %}
                    <p><strong>Biografia:</strong> {{ perfil.biografia }}</p>
                {% endif %}
                <p><strong>Privacidade:</strong> {{ perfil.get_privacidade_display }}</p>

                {% if seguidores_count > 0 %}
                    <p><strong>Seguidores:</strong> {{ seguidores_count }}</p>
                {% else %}
                    <p><strong>Seguidores:</strong> Nenhum seguidor</p>
                {% endif %}

                {% if seguindo_count > 0 %}
                    <p><strong>Seguindo:</strong> {{ seguindo_count }}</p>
                {% else %}
                    <p><strong>Seguindo:</strong> Não está seguindo ninguém</p>
                {% endif %}
            </div>
        {% elif bloquear_acesso %}
            <!-- Caso o perfil seja privado e o usuário não se siga com a pessoa -->
            <div class="info-bloco">
                <p><em>Este perfil é privado. Ambos os usuários precisam se seguir para visualizar as informações completas.</em></p>
            </div>
        {% else %}
            <!-- Exibe as informações completas caso ambos se sigam ou o perfil seja público -->
            <div class="info-bloco">
                <p><strong>Email:</strong> {{ usuario.email }}</p>
                {% if perfil.nascimento %}
                    <p><strong>Nascimento:</strong> {{ perfil.nascimento }}</p>
                {% endif %}
                {% if perfil.generos_musicas %}
                    <p><strong>Gêneros Musicais:</strong> {{ perfil.generos_musicas }}</p>
                {% endif %}
                {% if perfil.biografia %}
                    <p><strong>Biografia:</strong> {{ perfil.biografia }}</p>
                {% endif %}
                <p><strong>Privacidade:</strong> {{ perfil.get_privacidade_display }}</p>

                {% if seguidores_count > 0 %}
                    <p><strong>Seguidores:</strong> {{ seguidores_count }}</p>
                {% else %}
                    <p><strong>Seguidores:</strong> Nenhum seguidor</p>
                {% endif %}

                {% if seguindo_count > 0 %}
                    <p><strong>Seguindo:</strong> {{ seguindo_count }}</p>
                {% else %}
                    <p><strong>Seguindo:</strong> Não está seguindo ninguém</p>
                {% endif %}
            </div>
        {% endif %}


        {% if request.user == usuario %}
            <div class="button-group" style="margin-top: 20px;">
                <a href="{% url 'perfil_config' %}" class="btn-config">Configurações</a>
            </div>
        {% else %}
            <div class="button-group" style="margin-top: 20px;">
                {% if is_following %}
                    <button id="follow-btn" class="btn btn-success">Seguindo</button>
                {% else %}
                    <button id="follow-btn" class="btn btn-primary">Seguir</button>
                {% endif %}
            </div>
        {% endif %}
    </div>

    <nav class="navbar">
        <a href="{% url 'principal' %}"><i class="fa-solid fa-house"></i> Home</a>
        <a href="{% url 'buscar_musicas' %}"><i class="fas fa-search"></i> Buscar</a>
        <a href="{% url 'listar_playlists' %}"><i class="fas fa-book"></i> Biblioteca</a>
        <a href="{% url 'my_communities' %}"><i class="fas fa-users"></i> Comunidade</a>
        <a href="{% url 'perfil' request.user.username %}"><i class="fas fa-user"></i> Perfil</a>
    </nav>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#follow-btn').click(function() {
                const btn = $(this);
                $.ajax({
                    url: "{% url 'seguir' %}",
                    method: 'POST',
                    data: {
                        'user_id': "{{ usuario.id }}",
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(response) {
                        if (response.status === 'followed') {
                            btn.text('Seguindo');
                            btn.removeClass('btn-primary').addClass('btn-success');
                        } else if (response.status === 'unfollowed') {
                            btn.text('Seguir');
                            btn.removeClass('btn-success').addClass('btn-primary');
                        }
                    },
                    error: function() {
                        alert('Erro ao tentar seguir/desseguir usuário.');
                    }
                });
            });
        });
    </script>
</body>
</html>